import { existsSync, mkdirSync, writeFileSync } from 'fs';
import type { NextConfig } from 'next';
import { basename, dirname, join } from 'path';
import { loggers } from 'peam/logger';
import { defaultConfig, PeamAdapterConfig, setNextConfig } from './config';

const log = loggers.next;

/**
 * Wraps Next.js config to enable Peam content extraction during build.
 *
 * @example
 * ```typescript
 * // next.config.ts
 * import { withPeam } from '@peam-ai/next';
 *
 * export default withPeam()({
 *   // your Next.js config
 * });
 * ```
 */
export function withPeam(peamConfig?: PeamAdapterConfig) {
  return function (nextConfig: NextConfig = {}): NextConfig {
    const config = {
      ...defaultConfig,
      ...peamConfig,
    };

    setNextConfig(nextConfig, config);

    const projectRoot = process.cwd();
    const indexDir = dirname(config.indexPath);
    const indexFilename = basename(config.indexPath);
    const peamPath = join(projectRoot, indexDir);
    const peamIndexExists = existsSync(join(peamPath, 'index.js'));

    // Create stub files if they don't exist yet
    if (!peamIndexExists) {
      try {
        mkdirSync(peamPath, { recursive: true });

        writeFileSync(join(projectRoot, config.indexPath), JSON.stringify({ data: {}, keys: [] }, null, 2));

        writeFileSync(
          join(peamPath, 'index.js'),
          '// Auto-generated by Peam - DO NOT EDIT THIS FILE\n' +
            `import index from "./${indexFilename}";\n` +
            'export default index;\n'
        );

        log.debug('Created stub index files. Run build to generate actual search index.');
      } catch (error) {
        log.warn('Could not create stub files:', error);
        log.warn('Search functionality will not work until build completes.');
      }
    }

    const indexPath = `./${indexDir}`;

    return {
      ...nextConfig,
      experimental: {
        ...nextConfig.experimental,
        adapterPath: require.resolve('../dist/peam.adapter.js'),
      },
      turbopack: {
        ...(nextConfig.turbopack || {}),
        resolveAlias: {
          ...(nextConfig.turbopack?.resolveAlias || {}),
          'peam_index/generated': indexPath,
        },
      },
      webpack(webpackConfig, ctx) {
        if (!webpackConfig.resolve) {
          webpackConfig.resolve = {};
        }
        if (!webpackConfig.resolve.alias) {
          webpackConfig.resolve.alias = {};
        }

        webpackConfig.resolve.alias = {
          ...webpackConfig.resolve.alias,
          'peam_index/generated': peamPath,
        };

        if (typeof nextConfig.webpack === 'function') {
          return nextConfig.webpack(webpackConfig, ctx);
        }

        return webpackConfig;
      },
    };
  };
}
