packages:
  - packages/*
  - docs

overrides:
  '@mozilla/readability@<0.6.0': '>=0.6.0'
  diff@<8.0.3: '>=8.0.3'
  esbuild@<=0.24.2: '>=0.25.0'
  happy-dom@<20.0.0: '>=20.0.0'

onlyBuiltDependencies:
  - esbuild
  - bun
